control: rules: Avoid accessing outside internet for OBS build
The OBS builds failed with the Rust's Cargo error:

[0/1] Generating src/cargo-build with a custom command
    Updating crates.io index
error: Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  SSL error: 0xffff8780 - SSL - The peer notified us that the connection is going to be closed; class=Ssl (16)
FAILED: src/gnome-tour
/usr/bin/env CARGO_HOME=/src/_build/cargo-home /usr/bin/cargo build --manifest-path /src/Cargo.toml --target-dir /src/_build/src --release && cp src/release/gnome-tour src/gnome-tour

It cannot pull libraries from GitHub, because OBS cannot access outside
internet.

This commit makes gnome-tour depend on cargo, instead of dh-cargo by
following the commit ("Update debian/rules to fix build without
Internet") [1]. Also, takes the debian/rules modification, but keeps
Cargo's home, Registry, lock and config prepared by eos-build. These
avoid the build process accessing outside internet on OBS.

[1]: https://salsa.debian.org/gnome-team/gnome-tour/-/commit/822944c93de6b0e5f68ebdd806b83d5fb0593424

https://phabricator.endlessm.com/T35075